### PR TITLE
Fix index links, add links to tools/resources about regexes

### PR DESCRIPTION
**Pull request by winterthediplomat**
Some links in the index were outdated, or didn't have a corresponding anchor tag.

This patch also adds a list of tools and resources (books, internet articles) to check when you have to test a regular expression, or just want to study this interesting tool.

### CODE REVIEW

**Comment by OpenCode** [comment]
Please, remove "Know more about Regular Expressions" section. This is a repo only for ready to use regex. It can be added to this repo: https://github.com/aloisdg/awesome-regex.

Other corrections are ok! Remove useles section so I can accept the pull request ;)

**Comment by winterthediplomat** [comment]
Reverted last commit.
I was not aware of the other `awesome-regex` project, I'll take a look at it.

**Comment by OpenCode** [comment]
Re-add the twitter status regex, please.

**Comment by OpenCode** [comment]
Please, fix backslash escaping:

```
https?:\/\/twitter.com\/[a-z0-9_]+\/status\/[0-9]+
```

**Comment by winterthediplomat** [comment]
it should be ok now.

**Pull request merged**
